services:
  - docker
sudo: true
language: rust
rust:
  - nightly
cache: cargo

install:
    - ./ci/install_just.sh

jobs:
  include:
    - stage: build, run checks, test
      script: just test-release
    - stage: build docker image for the development branch
      if: branch = develop AND type = push
      script: just docker-image-develop
    - stage: release
      if: branch = master AND type = push
      script: just release-ci && just docker-image-release
