services:
  - docker

language: rust
rust:
  - nightly
cache: cargo

jobs:
  include:
    - stage: build
      script: cargo build --verbose
    - stage: test
      script: cargo test --verbose
    - stage: docker-image-dev
      if: branch = development
      script: ./scripts/docker-image-release.sh development
    - stage: docker-image-release
      if: branch = master AND type = push
      script: ./scripts/docker-image-release.sh
    - stage: binary-release
      if: branch = master AND type = push
      script: ./scripts/binary-release.sh