services:
  - docker
sudo: true
language: rust
rust:
  - nightly
cache: cargo

install:
    - ./ci/install_just.sh

jobs:
  include:
    - stage: build
      script: just build-release
    - stage: test
      script: just test-release
    - stage: docker image development
      if: branch = develop AND type = push
      script: just docker-image-develop
    - stage: release
      if: branch = master AND type = push
      script: just release-ci 1.0.0
