services:
  - docker

language: rust
rust:
  - nightly
cache: cargo

install:
    - cargo install just

jobs:
  include:
    - stage: build
      script: just build-release
    - stage: test
      script: just test
    - stage: docker image development
      if: branch = develop AND type = push
      script: just docker-image-develop
    - stage: binary artifact
      if: branch = master AND type = push
      script: just binary-artifact
    - stage: docker image release
      if: branch = master AND type = push
      script: just docker-image-release
