services:
  - docker
sudo: true
language: rust
rust:
  - nightly
cache: cargo

before_install:
    sudo apt install nix

install:
    - nix-env -i just

jobs:
  include:
    - stage: build
      script: just build-release
    - stage: test
      script: just test
    - stage: docker image development
      if: branch = develop AND type = push
      script: just docker-image-develop
    - stage: binary artifact
      if: branch = master AND type = push
      script: just binary-artifact
    - stage: docker image release
      if: branch = master AND type = push
      script: just docker-image-release
