FROM alpine

LABEL com.cezarmathe.feeder-author="Armand Cezar Mathe <cezarmathe [at] gmail [dot] com>"

WORKDIR /

COPY ./target/release/feeder /feeder

ENV DB_HOST="localhost"
ENV DB_PORT=27017

EXPOSE 8000
ENTRYPOINT /feeder
