FROM rustlang/rust:nightly

MAINTAINER Armand Cezar Mathe <cezarmathe [at] gmail [dot] com>

RUN mkdir feeder
WORKDIR /feeder

COPY . .

RUN cargo build --release
RUN cp target/release/feeder feeder

ENV DB_HOST="localhost"
ENV DB_PORT=27017

EXPOSE 8000
ENTRYPOINT /feeder
